webapp/portmanager_project/portmanager/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.i18n import JavaScriptCatalog

admin.autodiscover()


js_info_dict = {
    'packages': ('switches',),
}

urlpatterns = [
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('switches.urls')),
]

webapp/portmanager_project/switches/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

from . import views

app_name = 'switches'

urlpatterns = [
                  url(r'^log.html', views.show_user_log, name='log'),
                  url(r'^index.html', views.index, name='index'),
                  url(r'^export.html', views.display_export, name='export'),
                  url(r'^profile.html', views.display_profile, name='profile'),
                  url(r'^port_move.html', views.display_port_move, name='port_move'),
                  url(r'^guide.html', views.display_guide, name='guide'),
                  url(r'^guide_usr.html', views.display_guide_usr, name='guide_usr'),
                  url(r'^guide_dev.html', views.display_guide_dev, name='guide_dev'),
                  url(r'^guide_local.html', views.display_guide_local, name='guide_local'),
                  # AJAX calls:
                  url(r'^get_connected_macs', views.get_connected_macs),
                  url(r'^export_csv', views.export_csv),
                  url(r'^get_cached_ports', views.get_cached_ports),
                  url(r'^get_devices', views.get_devices),
                  url(r'^get_switches_by_location', views.get_switches_by_location),
                  url(r'^get_switch_permissions', views.get_switch_permission),
                  url(r'^show_switch_definitions', views.show_switch_definitions),
                  url(r'^get_switch_group_permission', views.get_switch_group_permission),
                  url(r'^change_port_alias', views.change_alias),
                  url(r'^turn_on_off_port', views.turn_on_off),
                  url(r'^apply_port_default_config', views.apply_port_default_config),
                  url(r'^change_vlan', views.change_vlan),
                  url(r'^transfer_port_settings', views.transfer_port_settings),
                  url(r'^transfer_switch', views.transfer_switch),
                  url(r'^get_switch_information', views.return_switch_information),
                  url(r'^getStatement', views.return_all_locks),
                  url(r'^get_changeable_information', views.get_port_information),
                  url(r'^manage_users.html', views.manage_users, name='manage_users'),
                  url(r'^manage_groups.html', views.manage_groups, name='manage_groups'),
                  url(r'^get_group_users', views.get_group_users, name='get_group_users'),
                  url(r'^get_group_admins', views.get_group_admins, name='get_group_admins'),
                  url(r'^manage_switches.html', views.manage_switches, name='manage_switches'),
                  url(r'^manage_default_port_config.html', views.manage_default_port_config, name='manage_default_port_config'),
                  url(r'^logger.html', views.show_log, name='logger'),
                  url(r'^manage_ports.html', views.manage_ports, name='manage_ports'),
                  url(r'^manage_vlans.html', views.manage_vlans, name='manage_vlans'),
                  url(r'^manage_location.html', views.manage_location, name='manage_location'),
                  # AJAX calls:
                  url(r'^generate_all_groups', views.generate_all_groups),
                  url(r'^load_portvlan_data', views.load_portvlan_data),
                  url(r'^load_switch_groups', views.load_switch_groups),
                  url(r'^generate_switch_groups', views.generate_all_groups),
                  url(r'^load_switches_available_for_portvlan', views.load_switches_available_for_portvlan),
                  url(r'^create_acc', views.create_acc),
                  url(r'^update_acc', views.update_acc),
                  url(r'^add_user_to_group', views.add_user_to_group),
                  url(r'^add_admin_to_group', views.add_admin_to_group),
                  url(r'^add_portvlan', views.add_portvlan),
                  url(r'^remove_user_from_group', views.remove_user_from_group),
                  url(r'^remove_admin_from_group', views.remove_admin_from_group),
                  url(r'^remove_group', views.remove_group),
                  url(r'^create_group', views.create_group),
                  url(r'^update_group_name', views.update_group_name),
                  url(r'^update_ports_def_name', views.update_ports_def_name),
                  url(r'^remove_user', views.remove_user),
                  url(r'^create_switch', views.create_switch),
                  url(r'^create_location', views.create_location),
                  url(r'^create_device', views.create_device),
                  url(r'^remove_switch', views.remove_switch),
                  url(r'^remove_portvlan', views.remove_portvlan),
                  url(r'^change_statement', views.change_statement),
                  url(r'^change_statement_pv', views.change_statement_pv),
                  url(r'^save_portvlan_def_name', views.save_portvlan_def_name),
                  url(r'^add_device_to_portvlan_def', views.add_device_to_portvlan_def),
                  url(r'^remove_device_from_portvlan_def', views.remove_device_from_portvlan_def),
                  url(r'^add_group_to_portvlan_def', views.add_group_to_portvlan_def),
                  url(r'^delete_group_from_portvlan_def', views.delete_group_from_portvlan_def),
                  url(r'^change_visibility', views.change_visibility),
                  url(r'^change_regex', views.change_regex),
                  url(r'^change_poe_regex', views.change_poe_regex),
                  url(r'^change_ssh_key', views.change_ssh_key),
                  url(r'^add_reply', views.add_reply),
                  url(r'^load_more_logs', views.load_more_logs),
                  url(r'^update_switch_address', views.update_switch_address),
                  url(r'^update_switch_name', views.update_switch_name),
                  url(r'^update_location_name', views.update_location_name),
                  url(r'^update_switch_location', views.update_switch_location),
                  url(r'^update_switch_device', views.update_switch_device),
                  url(r'^update_switch_community_string', views.update_switch_community_string),
                  url(r'^update_switch_snmp', views.update_switch_snmp),
                  url(r'^update_device_default_port_config', views.update_device_default_port_config),
                  url(r'^update_max_port_sec', views.update_max_port_sec),
                  url(r'^update_port_sec', views.update_port_sec),
                  url(r'^reload_cache', views.reload_cache),
                  url(r'^get_poe_data', views.get_poe_data),
                  url(r'^$', views.index),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

webapp/portmanager_project/switches/views.py
import json
import logging
import os
from subprocess import call

import configparser
from django.core import serializers
from django.core.cache import cache
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from django.utils.translation import ugettext

import services
import users
from time import sleep
from logger import Logger
from models import *
from switch_modules.general import SessionError

logger = logging.getLogger(__name__)


def get_switch_permission(request):
    """

    :param request:
    :return:
    """
    switch = request.POST['switch_id']

    try:
        user = request.POST['user_id'].id_person
        account = users.login(user)
    except Exception:
        account = users.login(request)

    user = account[1]
    groups = users.from_uco_load_groups(user.id_person)
    switch = Switch.objects.get(id_switch=switch)

    user_ports = Ports.objects.all()
    user_ports = user_ports.filter(switch=switch, groups__in=groups).distinct()
    switch_instance = services.get_instance(switch)

    existing_ports = switch_instance.get_port_descriptions()
    output_structure = []

    def update_permission(default, new):
        # 0 - no access
        # 1 - view_only
        # 2 - read_write
        permission_array = [0, 1, 2]

        if default in permission_array and new in permission_array:
            if new > default:
                return new
            else:
                return default
        else:
            raise TypeError("Default and new must be in range(0,2)")

    # existing_ports = map(lambda x: [x[0],x[1],0], existing_ports)
    temp_hash = {}

    for key in existing_ports.iterkeys():
        value = existing_ports[key]
        temp_hash[key] = [value, 0]
    existing_ports = temp_hash

    for group_of_ports in user_ports:
        regex_instance = users.RegExp(group_of_ports.regex)
        array = regex_instance.getStringArray()
        # have to differentiate between ports containing single or multiple ports

        for ports in array:
            if ports == '':
                continue
            if '-' in ports:
                start = int(ports.split('-')[0])
                end = int(ports.split('-')[1])

                for i in range(start, end + 1):
                    if str(i) not in existing_ports:
                        continue
                    value = existing_ports[str(i)]
                    if group_of_ports.view_only:
                        existing_ports[str(i)] = [
                            value[0], update_permission(value[1], 1)]
                    else:
                        existing_ports[str(i)] = [
                            value[0], update_permission(value[1], 2)]
            else:
                if str(ports) not in existing_ports:
                    continue
                value = existing_ports[str(ports)]
                if group_of_ports.view_only:
                    existing_ports[str(ports)] = [
                        value[0], update_permission(value[1], 1)]
                else:
                    existing_ports[str(ports)] = [
                        value[0], update_permission(value[1], 2)]

    for key in existing_ports.iterkeys():
        value = existing_ports[str(key)]
        output_structure.append([key, value[0], value[1]])
    output_structure.sort(key=lambda x: int(x[0]))

    return HttpResponse(json.dumps(output_structure))


def show_switch_definitions(request):
    """

    :param request:
    :return:
    """
    switch = request.POST['switch_id']

    try:
        user = request.POST['user_id'].id_person
        account = users.login(user)
    except Exception:
        account = users.login(request)

    user = account[1]
    groups = users.from_uco_load_groups(user.id_person)
    switch = Switch.objects.get(id_switch=switch)

    user_ports = Ports.objects.all()
    user_ports = user_ports.filter(switch=switch, groups__in=groups).distinct()
    user_vlans = Vlans.objects.all()
    user_vlans = user_vlans.filter(switch=switch, groups__in=groups).distinct()

    output_structure = '<h3>Port:</h3> <br>'
    for port in user_ports:
        output_structure = output_structure + str(port) + '<br>'
    output_structure = output_structure + '<h3>VLAN:</h3> <br>'
    for vlan in user_vlans:
        output_structure = output_structure + str(vlan) + '<br>'

    return HttpResponse(output_structure)


def show_user_log(request):
    """
    Returns logs of users
    :param request:
    :return:
    """
    account = users.login(request)
    user = account[1]
    adm_groups = users.is_admin(account[0])
    logs = Event.objects.all()
    logs = logs.filter(who=user).order_by("-id_event")

    return render(request, "user_log.html",
                  {"user": user, "logs": logs, 'adm_groups': adm_groups})


def index(request):
    """
    Primary method to show all switches and give user access to change settings
    :param request:
    :return:
    """
    account = users.login(request)
    uco = account[0]
    user = account[1]

    if request.method == "GET":
        # loads unseen comments and unseen events from Event, then set those events as seen
        events = Event.objects.all().filter(who=user, seen=False)
        events_to_display = events

        for event in events:
            event.seen = True
            event.save()

        groups = users.from_uco_load_groups(uco)
        adm_groups = users.is_admin(uco)

        # order_by makes sure that switches from one locations are listed together and alphabetically
        switches = Switch.objects.all().order_by('location', 'name')
        switches = switches.filter(owners__in=groups).distinct()

        if not switches:
            string = ugettext(
                'You do not have permissions to any device, '
                'please contact the administrator to assign rights to your location.')
            link = "/portmanager/account/index.html"
            return render(request, 'report.html',
                          {'string': string, 'user': user, 'link': link, 'adm_groups': adm_groups})

        locations = Location.objects.all().filter(switch__in=switches).distinct()
        keys = []
        for location in locations:
            if len(cache.keys('port_' + str(location.id_location) + '_*')) > 0:
                keys.extend(cache.keys('port_' + str(location.id_location) + '_*'))
        cached_ports = []
        cached_results = cache.get_many(keys)
        for port_id, port_val in cached_results.items():
            if not port_val:
                port_val = '(None)'
            cached_ports.append(port_id + '_' + port_val)
        # switches = sorted(switches, cmp=location_sort)
        return render(request, 'index.html',
                      {'switches': switches,
                       'user': user,
                       'events': events_to_display,
                       'locations': locations,
                       'adm_groups': adm_groups,
                       'cached_ports': cached_ports,
                       })


def return_switch_information(request):
    """ AJAX instantly changes currently changes data to other users

    :param request: switch ID
    :return: returns JSON with information about ports
    """
    account = users.login(request)
    uco = account[0]
    user = account[1]
    person = Person.objects.get(id_person=int(uco))
    read_only = person.read_only
    portsec_modify = person.port_sec

    config = configparser.ConfigParser()
    config.read('/srv/config/app_config.ini')
    max_port_sec = config['app']['max_allowed_devices']

    switch = Switch.objects.get(id_switch=request.POST['id'])
    groups = users.from_uco_load_groups(uco)

    ports = Ports.objects.all()
    ports = ports.filter(switch=switch, groups__in=groups).distinct()
    # select ports with access of user
    # we have to create list of ports to prevent duplicates
    # because of this read permission must be rewritten by write permission
    # if user has both

    poe_ports = []
    if switch.poe_regex:
        try:
            poe_regex_instance = users.RegExp(switch.poe_regex)
            poe_array = poe_regex_instance.getStringArray()
            if poe_array is not None and poe_array != [""]:
                for ports in poe_array:
                    poe_ports.append(ports)
        except:
            print "no poe ports"
    switch_instance = services.get_instance(switch)
    json_structure = {}
    poe_ports_table = ""
    try:
        switch.template_info = switch_instance.render_ports(user)
        switch.template_info = switch_instance.render_vlans(user)
    except Exception as e:
        json_structure['error'] = str(e)
        logger.error(str(e))
        return HttpResponse(json.dumps(json_structure, separators=(',', ':')), content_type='application/javascript')
    try:
        poe_ports_table = switch_instance.get_port_pwr_consumption(poe_ports)
    except Exception as e:
        logger.error(str(e))
    poe_ports_dict = {}

    if poe_ports_table is not None:
        for port in poe_ports_table:
            port_splitted = port.split(': ')
            poe_ports_dict[port_splitted[0]] = str(float(port_splitted[1])/1000)
        json_structure['poe_ports'] = poe_ports_dict
    json_structure['ports'] = switch.template_info.porty
    json_structure['vlans'] = switch.template_info.vlany
    json_structure['switch_id'] = switch.id_switch
    json_structure['read_only'] = read_only
    json_structure['portsec_modify'] = portsec_modify
    json_structure['portsec_max'] = max_port_sec

    return HttpResponse(json.dumps(json_structure, separators=(',', ':')),
                        content_type='application/javascript')


def get_cached_ports(request):
    """
    Retrieves ports from Redis cache used for global searching
    :param request:
    :return:
    """
    account = users.login(request)
    uco = account[0]
    query_string = request.META['QUERY_STRING'].split('q=')[1]

webapp/portmanager_project/switches/templates/adminlte/lib/_main_footer.html
{% extends 'adminlte/lib/_main_footer.html' %}
{% load i18n %}

{% block footer_right %}
    <b>Version</b>{% block version %} 2.0{% endblock %}
{% endblock %}

{% block legal %}
    <strong>Copyright &copy; {% now "Y" %}
        {% if LANGUAGE_CODE == 'en' %}
            <a href="http://www.ics.muni.cz/en">{% trans "ICS MUNI" %}</a>
        {% else %}
            <a href="http://www.ics.muni.cz/">{% trans "ICS MUNI" %}</a>
        {% endif %}
    </strong>
{% endblock %}

webapp/portmanager_project/switches/templates/adminlte/lib/_main_header.html
{% extends 'adminlte/lib/_main_header.html' %}
{% load staticfiles %}
{% load i18n %}

{% block logo %}
    <a href="{% block logo_href %}/{% endblock %}" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>PM</b></span>
        <!-- logo for regular state and mobile devices -->

        <span class="logo-lg"><img src="{% static "switches/pm_logo.png" %}" alt="AdminLTE Docs Logo Large" class="brand-image-xs logo-xl" style="left: 12px"></span>
    </a>
{% endblock %}

{% block nav_bar %}
    <nav class="navbar navbar-static-top">
        <a href="#" class="sidebar-toggle" id="header-sandwich-button" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>

        {% block nav_bar_center %}

            <div class="navbar-custom-menu">

                <ul class="nav navbar-nav">
                    <li>
                        <a href="#" id="change_lang"><i class="fa fa-language" title="EN/CZ"></i></a>
                        <input id="current_lang" type="hidden" value={{ LANGUAGE_CODE }}/>
                    </li>
                </ul>
            </div>

        {% endblock %}
    </nav>


{% endblock %}

webapp/portmanager_project/switches/templates/adminlte/lib/_main_sidebar.html
{% extends 'adminlte/lib/_main_sidebar.html' %}
{% load staticfiles %}
{% load i18n %}

{% block user_panel %}

    <div class="user-panel">
        <div class="pull-left image">
            <img src="{% static "switches/avatar.png" %}" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
            <p>{{ user.name }} {{ user.surname }}</p>
            {% if user.superuser %}
                <p>({% trans "Admin" %})</p>
            {% else %}
                <p>({% trans "Regular user" %})</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block nav_links_ul %}
    <ul class="sidebar-menu" data-widget="tree">
        {% block nav_links %}
            <li class="header">{% trans "USER SECTION" %}</li>
            <li>
                <a href="{% url 'switches:index' %}">
                    <i class="fa fa-server"></i>
                    {% trans "Devices" %}
                </a>
            </li>
            <li>
                <a href="{% url 'switches:export' %}">
                    <i class="fa fa-download"></i>
                    {% trans "Data export" %}
                </a>
            </li>
            <li>
                <a href="{% url 'switches:log' %}">
                    <i class="fa fa-history"></i>
                    Log
                </a>
            </li>
            <li>
                <a href="{% url 'switches:profile' %}">
                    <i class="fa fa-cogs"></i>
                    {% trans "User settings" %}
                </a>
            </li>
            <li>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-question-circle"></i>
                    <span>{% trans "Help" %}</span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{% url 'switches:guide' %}">1. {% trans "Basic usage" %}</a></li>
                    <li><a href="{% url 'switches:guide_local' %}">2. {% trans "Local management" %}</a></li>
                    <li><a href="{% url 'switches:guide_usr' %}">3. {% trans "User management" %}</a></li>
                    <li><a href="{% url 'switches:guide_dev' %}">4. {% trans "Device management" %}</a></li>

                </ul>
            </li>

            {% if adm_groups %}
                <li>
                    <a href="{% url 'switches:manage_location' %}">
                        <i class="fa fa-question-circle"></i>
                        {% trans "Management" %}
                    </a>
                </li>
            {% endif %}
            {% if user.superuser %}
                <li class="header">{% trans "ADMINISTRATION" %}</li>
                <li>
                    <a href="{% url 'switches:manage_users' %}">
                        <i class="fa fa-user"></i>
                        {% trans "Users" %}
                    </a>
                </li>
                <li>
                    <a href="{% url 'switches:manage_groups' %}">
                        <i class="fa fa-users"></i>
                        {% trans "User Groups" %}
                    </a>
                </li>
                <li>
                    <a href="{% url 'switches:manage_default_port_config' %}">
                        <i class="fa fa-cogs"></i>
                        {% trans "App Configuration" %}
                    </a>
                </li>
                <li>
                    <a href="{% url 'switches:manage_switches' %}">
                        <i class="fa fa-server"></i>
                        {% trans "Switches" %}
                    </a>
                </li>
                <li>
                    <a href='{% url 'switches:manage_ports' %}'>
                        <i class="fa fa-square-o"></i>
                        {% trans "Ports" %}
                    </a>
                </li>
                <li>
                    <a href='{% url 'switches:manage_vlans' %}'>
                        <i class="fa fa-object-group"></i>
                        {% trans "Vlans" %}
                    </a>
                </li>

                <li>
                    <a href="{% url 'switches:logger' %}">
                        <i class="fa fa-address-book"></i>
                        Logger
                    </a>
                </li>
                <li>
                    <a href="/admin/">
                        <i class="fa fa-drivers-license"></i>
                        Django admin
                    </a>
                </li>
            {% endif %}
        {% endblock nav_links %}
    </ul>
{% endblock nav_links_ul %}